apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriovnetwork2
  namespace: openshift-sriov-network-operator
spec:
  networkNamespace: default
  ipam: | 
    {
      "type": "host-local",
      "subnet": "10.57.217.0/24",
      "rangeStart": "10.57.217.171",
      "rangeEnd": "10.57.217.181",
      "routes": [{
        "dst": "0.0.0.0/0"
      }],
      "gateway": "10.57.217.1"
    }
  vlan: 0
  resourceName: intelnics2
