apiVersion: v1
kind: Pod
metadata:
  name: testpod3
  annotations:
    k8s.v1.cni.cncf.io/networks: sriovnetwork2
spec:
  containers:
  - name: appcntr1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        openshift.io/intelnics2: '1'
      limits:
        openshift.io/intelnics2: '1'
